Shopping = ["Pan", "Leche", "Huevos"]
print("Lista inicial:")
print(Shopping)
Shopping.append("Queso")
Shopping.append("Yogurt")
print("\n Después de agregar Queso y Yogur:")
print(Shopping)
Shopping.insert(1, "Mantequilla")
print("\n Después de insertar Mantequilla en posición 1:")
print(Shopping)
Shopping.remove("Huevos")
print("\n Después de eliminar huevos:")
print(Shopping)
Delete_element = Shopping.pop(0)
print("\n Eliminamos el primer elemento:", Delete_element)
print("Lista final:", Shopping)